import { ModuleContent } from '../../types';

export const module8Data: ModuleContent = {
  id: 'module-8',
  number: 8,
  title: 'The Cash Flow Statement',
  subtitle: 'Reconciling profit with cash using the Direct Method: Operating, Investing, and Financing flows, and proving that closing cash equals the balance sheet.',
  sourceBadge: 'Based on Session 7 slides',
  estimatedMinutes: 40,
  objectives: [
    'Understand why a highly profitable business can still go bankrupt due to cash timing differences.',
    'Distinguish items that affect Profit but NOT Cash (non-cash: depreciation, provisions, stock variations) from items that affect Cash but NOT Profit (loan drawdowns, repayments, capital contributions, equipment purchases).',
    'Structure the Cash Flow Statement into its 3 economic pillars: Operating Activities (A), Investing Activities (B), and Financing Activities (C).',
    'Calculate Operating Cash Flow using the Direct Method (Collections from clients minus payments to suppliers, staff, interest, and taxes).',
    'Calculate Investing Cash Flow (Purchases and sales of PP&E, intangible and financial assets).',
    'Calculate Financing Cash Flow (New borrowings, loan repayments, capital increases, dividend disbursements).',
    'Perform the master consistency check: Net Change in Cash + Opening Cash = Closing Cash on the Balance Sheet!'
  ],
  youWillUseThisWhen: 'You tackle the capstone Part 3 of the final exam (the Beethoven case), preparing the forecast Cash Flow Statement and verifying that ending cash strictly matches line 512 on the forecast balance sheet.',
  whyItMatters: {
    economicPurpose: 'The Income Statement answers "Did we create economic wealth this year?" The Cash Flow Statement answers "Can we pay our bills tomorrow morning?" Tracking liquidity across Operating, Investing, and Financing activities reveals whether a business is self-sustaining or dependent on external loans.',
    statementImpacts: [
      {
        statement: 'Balance Sheet (Bilan)',
        impact: 'Cash and cash equivalents (Bank + Cash on hand) at the reporting date must match the final line of the Cash Flow Statement to the exact cent!'
      },
      {
        statement: 'Income Statement (Compte de résultat)',
        impact: 'The Cash Flow Statement explains the divergence between Net Income and Cash Generated by stripping out non-cash expenses and adjusting for working capital timing.'
      },
      {
        statement: 'Cash Flow Statement',
        impact: 'Synthesizes all cash movements into 3 streams: Operating Flow (A) + Investing Flow (B) + Financing Flow (C) = Net Change in Cash (D).'
      }
    ]
  },
  howItWorks: [
    {
      id: 'm8-s1',
      title: 'Profit vs Cash: The Two Dimensions of Business',
      explanation: `Why does Net Income NEVER equal Cash in the bank?
Because accounting operates on the ACCRUAL basis, not the cash basis. Two massive gaps separate Profit from Cash:

1. NON-CASH ITEMS (Affects Profit, Zero Cash Impact):
   • Depreciation expense (Dotation aux amortissements)
   • Impairment losses on assets (Dépréciations)
   • Provisions for risks and charges (Provisions pour risques)
   • Inventory changes (Variation des stocks)
   → These reduce or increase profit, but ZERO money enters or leaves the bank account!

2. CASH TIMING DIFFERENCES & CAPITAL OPERATIONS (Affects Cash, Zero Profit Impact):
   • Obtaining a new bank loan (+ Cash, 0 Profit)
   • Repaying loan principal (- Cash, 0 Profit)
   • Buying equipment / PP&E (- Cash, 0 Profit - capitalized!)
   • Contributing share capital (+ Cash, 0 Profit)
   • Paying dividends (- Cash, 0 Profit)
   • Timing lags: Sales made on credit (Revenues earned, but cash collected next month); Purchases made on supplier credit (Expense incurred, but cash paid next month).`,
      bulletPoints: [
        'Profit without cash leads to bankruptcy; cash without profit is merely borrowed time.',
        'Cash and cash equivalents include: Bank debit balances + Petty cash + Short-term liquid investments (≤ 3 months).'
      ],
      eli10: {
        id: 'eli10-m8-profit-cash',
        title: 'The Lemonade Stand IOUs',
        concept: 'Why Profit Does Not Equal Cash',
        analogy: 'Imagine on Monday you sell 100 cups of lemonade for €100. But all your neighborhood friends say: "We will pay you next Friday!" On Monday night, your Income Statement shows €100 of revenue and €80 of profit. But when you look inside your cash box, there is €0.',
        explanation: 'If your supplier arrives on Tuesday demanding €20 for lemons, you cannot pay him with your friends’ promises! You have plenty of profit on paper, but zero cash to survive the week.',
        keyDistinction: 'Profit is what you earned on paper; Cash is what is physically sitting in your cash box right now.',
        reconnect: 'The Cash Flow Statement tracks exactly when physical cash enters and leaves the business.'
      }
    },
    {
      id: 'm8-s2',
      title: 'The 3 Cash Streams (Direct Method Structure)',
      explanation: `Under the Direct Method taught in Session 7, the Cash Flow Statement is divided into 3 distinct economic streams:

1. OPERATING CASH FLOW (Flux de trésorerie de l’activité - A):
   Measures cash generated by core commercial activity:
   + Collections on prior-year trade receivables
   + Cash collected from current-year sales
   – Payments on prior-year trade payables
   – Payments for current-year operating expenses
   – Interest paid on borrowings
   – Income taxes paid relating to prior year
   = NET CASH FLOW FROM OPERATING ACTIVITIES [A]
   (Analysis: Must be positive! If negative, the business model burns cash and relies on loans to survive).

2. INVESTING CASH FLOW (Flux de trésorerie d’investissement - B):
   Measures capital investments in long-term production tools:
   – Purchases of non-current assets (PP&E, Intangible, Financial)
   + Proceeds from disposal of non-current assets
   = NET CASH FLOW FROM INVESTING ACTIVITIES [B]
   (Analysis: Usually negative in growing businesses investing in new equipment).

3. FINANCING CASH FLOW (Flux de trésorerie de financement - C):
   Measures movements with providers of capital (shareholders & lenders):
   + Capital increase in cash (Equity injection)
   + Proceeds from new borrowings (Loans drawn)
   – Repayment of borrowings (Principal repaid)
   – Dividends paid to shareholders
   = NET CASH FLOW FROM FINANCING ACTIVITIES [C]`,
      bulletPoints: [
        'Operating: Customers, suppliers, staff, interest, taxes.',
        'Investing: Equipment bought (-) and sold (+).',
        'Financing: New loans (+), loan repayments (-), capital (+), dividends (-).'
      ],
      eli10: {
        id: 'eli10-m8-streams',
        title: 'The Three Pipes of the Water Tank',
        concept: 'The 3 Cash Flow Streams',
        analogy: 'Think of your bank account as a water tank. Water flows in and out through 3 distinct pipes:\n• Pipe 1 (Operating): Daily lemonade sales filling the tank, and buying lemons and ice draining it.\n• Pipe 2 (Investing): Draining water to buy a shiny commercial juicer, or selling your old juicer.\n• Pipe 3 (Financing): Borrowing a bucket of water from Dad (loan) or paying Dad back with interest and dividends.',
        explanation: 'At the end of the year, you measure how much water was in the tank on January 1, add or subtract what passed through the 3 pipes, and the result must match the exact water level on December 31.',
        keyDistinction: 'Operating pipe is daily life; Investing pipe is building the future; Financing pipe is funding.',
        reconnect: 'Net Change = Operating (A) + Investing (B) + Financing (C).'
      }
    },
    {
      id: 'm8-s3',
      title: 'Reconciliation & The Master Consistency Check',
      explanation: `The final step of the Cash Flow Statement is the absolute sanity check:
FORMULA:
  Net Cash Flow from Operating Activities [A]
+ Net Cash Flow from Investing Activities [B]
+ Net Cash Flow from Financing Activities [C]
= Net Change in Cash and Cash Equivalents [D = A + B + C]
+ Cash and Cash Equivalents at Beginning of Period (01/01/N) [E]
= Cash and Cash Equivalents at End of Period (31/12/N) [F = D + E]

THE MASTER EXAM SANITY CHECK:
Cash at End of Period from CFS [F] 
MUST EQUAL EXACTLY:
Cash and Cash Equivalents from Balance Sheet (Active line 512 Bank + 53 Cash) [F]!

If CFS closing cash ≠ Balance Sheet closing cash, a transaction was misclassified, cash was omitted, or an arithmetic error occurred!`,
      diagramType: 'process-flow',
      bulletPoints: [
        'Closing Cash = Opening Cash + Net Change in Cash.',
        'CFS Closing Cash must match Balance Sheet Line 512 + 53.'
      ]
    }
  ],
  workedExamples: [
    {
      id: 'ex-m8-1',
      title: 'Preparing a Complete Forecast Cash Flow Statement (Beethoven / Windsurf S7 format)',
      facts: `Opening Balance Sheet as of January 1, 2026 shows Cash in Bank = €63,000.
During 2026, the company executes the following transactions:
1. Appropriates 2025 net income: €5,000 paid as dividends in cash.
2. Collects €5,000 of prior-year trade receivables.
3. Pays €17,000 of prior-year trade payables.
4. Pays €10,000 of prior-year income tax liabilities.
5. Sales revenues for 2026: €400,000, of which €380,000 is collected in cash.
6. Purchases for 2026: €87,000, of which €70,000 is paid in cash.
7. External services paid in cash: €74,000.
8. Personnel expenses paid in cash: €170,000.
9. PP&E acquired and paid in cash: €5,000.
10. Interest expense paid in cash: €2,000.
11. Repayment of bank borrowings (principal): €5,000.
12. Depreciation expense for the year: €13,000 (non-cash).`,
      question: 'Calculate: (1) Operating Cash Flow, (2) Investing Cash Flow, (3) Financing Cash Flow, (4) Net Change in Cash, and (5) Closing Cash balance as of December 31, 2026.',
      concept: 'Direct Method Cash Flow Statement and statement reconciliation.',
      method: 'Group cash movements into Operating, Investing, and Financing activities, ignoring non-cash depreciation.',
      steps: [
        'Step 1 - Operating Cash Flow [A]:\n+ Cash collected on prior receivables: +5,000\n+ Cash collected on 2026 sales: +380,000\n– Cash paid on prior payables: -17,000\n– Cash paid on prior income tax: -10,000\n– Cash paid for 2026 purchases: -70,000\n– Cash paid for external services: -74,000\n– Cash paid for personnel: -170,000\n– Interest paid: -2,000\n= Net Operating Cash Flow [A] = 385,000 – 343,000 = +€42,000.',
        'Step 2 - Investing Cash Flow [B]:\n– Acquisition of PP&E: -5,000\n= Net Investing Cash Flow [B] = -€5,000.',
        'Step 3 - Financing Cash Flow [C]:\n– Dividends paid: -5,000\n– Repayment of borrowings: -5,000\n= Net Financing Cash Flow [C] = -€10,000.',
        'Step 4 - Note on Non-Cash items:\nDepreciation expense (€13,000) is completely ignored in the CFS because zero cash was paid.',
        'Step 5 - Net Change in Cash [D]:\nNet Change = A (+42,000) + B (-5,000) + C (-10,000) = +€27,000.',
        'Step 6 - Closing Cash Reconciliation [F]:\nClosing Cash = Opening Cash (€63,000) + Net Change (+€27,000) = €90,000.',
        'Check: Balance Sheet line 512 Bank as of 31/12/2026 must display exactly €90,000.'
      ],
      profitEffect: 'Non-cash depreciation (€13k) reduces Net Profit in P&L, but has 0 effect on cash.',
      positionEffect: 'Ending Bank balance increases by €27,000 from €63,000 to €90,000.',
      conclusion: 'Operating activities generated strong positive cash flow (+€42,000), which funded capital investments (-€5,000), dividend distributions (-€5,000), and debt repayment (-€5,000), leaving net cash up €27,000.',
      commonWrongTurn: 'Including depreciation expense in the Cash Flow Statement, or classifying dividend payments as operating rather than financing activities.'
    }
  ],
  whatMustIRemember: {
    keyTerms: [
      {
        term: 'Cash Flow Statement (CFS)',
        definition: 'Financial statement explaining the change in cash and cash equivalents between two balance sheet dates.',
        category: 'concept'
      },
      {
        term: 'Operating Cash Flow (Flux d’activité)',
        definition: 'Cash generated or consumed by daily core operations (sales collections minus operating disbursements).',
        category: 'concept'
      },
      {
        term: 'Investing Cash Flow (Flux d’investissement)',
        definition: 'Cash allocated to the purchase of fixed assets or received from asset disposals.',
        category: 'concept'
      },
      {
        term: 'Financing Cash Flow (Flux de financement)',
        definition: 'Cash movements with shareholders (capital, dividends) and lenders (borrowings, repayments).',
        category: 'concept'
      }
    ],
    formulas: [
      {
        name: 'Net Change in Cash',
        formula: 'Net Change = Operating CF [A] + Investing CF [B] + Financing CF [C]',
        note: 'Sum of the three direct streams.'
      },
      {
        name: 'Ending Cash Balance',
        formula: 'Ending Cash = Beginning Cash + Net Change in Cash',
        note: 'Must equal ending Bank + Petty Cash on the Balance Sheet.'
      }
    ],
    doNotConfuse: [
      {
        termA: 'Repayment of Loan Principal',
        termB: 'Payment of Loan Interest',
        keyDifference: 'Principal repayment is a FINANCING cash flow; Interest payment is an OPERATING cash flow (or financial P&L cost).',
        example: 'Instalment of €5,500 (€5,000 principal + €500 interest): €5,000 is Financing; €500 is Operating.'
      },
      {
        termA: 'Purchase of Equipment',
        termB: 'Depreciation of Equipment',
        keyDifference: 'Purchase is an INVESTING cash outflow on day 1; Depreciation is a subsequent NON-CASH expense with 0 cash impact.',
        example: 'Buying truck for €20k = -€20k Investing CF; Annual depr of €4k = €0 in CFS.'
      }
    ],
    commonTraps: [
      'Including non-cash items (depreciation, provisions, inventory variations) in the direct-method CFS.',
      'Putting equipment purchases in Operating Cash Flow. (Equipment purchases belong in Investing!).',
      'Forgetting that dividends paid belong in Financing Cash Flow.'
    ],
    memoriseThis: 'CFS = Operating (A) + Investing (B) + Financing (C). Non-cash depreciation is EXCLUDED! Closing CFS Cash MUST EQUAL Closing Balance Sheet Cash!'
  },
  moduleLevelEli10: {
    id: 'eli10-m8-module',
    title: 'The Water Tank and the Bank Account',
    concept: 'Module 8 Synthesis: The Cash Flow Statement',
    analogy: 'Imagine your bank account is a pool of water. On January 1, the water is at the 10-foot mark. During the year, customers pour buckets of water in and you scoop buckets out to pay workers (Operating pipe). You scoop out a huge bucket to buy a fancy ice cream maker (Investing pipe). You take a bucket from the bank loan officer and give a small bucket to your mom for helping fund you (Financing pipe).',
    explanation: 'On December 31, you dip a measuring stick into the pool. If your stick says 14 feet, your three pipes MUST explain why the water level rose by exactly 4 feet. If the pipes say +5 feet and your stick says 14 feet, you made a mistake!',
    keyDistinction: 'Paper profit tells you how clever your business was; the measuring stick tells you if you can swim.',
    reconnect: 'This absolute match between the Cash Flow Statement and Balance Sheet Line 512 is the final check of financial accounting.'
  },
  quiz: [
    {
      id: 'm8-q1',
      moduleId: 'module-8',
      sourceTopic: 'CFS Section for Equipment Purchase',
      type: 'mcq',
      difficulty: 'foundation',
      question: 'In the Cash Flow Statement (direct method), the acquisition of a delivery van paid in cash is classified under:',
      options: [
        'Operating Cash Flow',
        'Investing Cash Flow (Flux d’investissement)',
        'Financing Cash Flow',
        'It is excluded because it is a fixed asset'
      ],
      correctAnswer: '1',
      rationale: 'Acquiring property, plant, and equipment (PP&E) represents a long-term capital allocation, which belongs strictly to Investing Cash Flow (Flux d’investissement) as a disbursement.',
      misconceptionTargeted: 'Classifying fixed asset purchases as operating expenses.',
      revisitSection: '3.2 The 3 Cash Streams'
    },
    {
      id: 'm8-q2',
      moduleId: 'module-8',
      sourceTopic: 'Cash vs Profit Non-Cash Items',
      type: 'mcq',
      difficulty: 'foundation',
      question: 'Which of the following items affects Net Income (Profit or Loss) but has NO impact on cash flow?',
      options: [
        'Obtaining a new bank loan',
        'Recording the annual depreciation expense of equipment',
        'Paying cash dividends to shareholders',
        'Repaying the principal of a loan'
      ],
      correctAnswer: '1',
      rationale: 'Depreciation expense is an internal non-cash accounting allocation. It reduces net income in the Income Statement, but zero cash is disbursed. Loans, dividends, and repayments all move physical cash without being operating expenses.',
      misconceptionTargeted: 'Confusing non-cash accounting expenses with cash disbursements.',
      revisitSection: '3.1 Profit vs Cash'
    },
    {
      id: 'm8-q3',
      moduleId: 'module-8',
      sourceTopic: 'Loan Instalment Classification in CFS',
      type: 'mcq',
      difficulty: 'application',
      question: 'On September 30, a company pays a bank debit notice of €5,500, covering €5,000 of loan principal repayment and €500 of interest expense. How are these two amounts classified in the Cash Flow Statement?',
      options: [
        'The full €5,500 is classified under Financing Cash Flow',
        'The full €5,500 is classified under Operating Cash Flow',
        'The €5,000 principal repayment is Financing Cash Flow; the €500 interest is Operating Cash Flow',
        'The €5,000 is Investing Cash Flow; the €500 is Financing Cash Flow'
      ],
      correctAnswer: '2',
      rationale: 'Repaying loan principal is a financing activity (repaying capital to lenders). Paying interest is an operating cash flow (the ongoing operational cost of servicing debt).',
      misconceptionTargeted: 'Lumping interest and principal into the same cash flow stream.',
      revisitSection: '3.2 The 3 Cash Streams'
    },
    {
      id: 'm8-q4',
      moduleId: 'module-8',
      sourceTopic: 'Master Consistency Check',
      type: 'true-false',
      difficulty: 'foundation',
      question: 'The closing cash and cash equivalents reported at the bottom of the Cash Flow Statement must exactly equal the cash and bank balance reported on the Balance Sheet.',
      options: ['Agree / True', 'Disagree / False', 'Don’t know'],
      correctAnswer: '0',
      rationale: 'Agree / True. The fundamental consistency check required on all exams (including Beethoven) is that CFS Ending Cash = Balance Sheet Ending Cash (Line 512 Bank + Line 53 Cash).',
      misconceptionTargeted: 'Believing the Cash Flow Statement can have a different closing cash figure than the Balance Sheet.',
      revisitSection: '3.3 Reconciliation & Master Consistency Check'
    },
    {
      id: 'm8-q5',
      moduleId: 'module-8',
      sourceTopic: 'Operating Cash Flow Significance',
      type: 'mcq',
      difficulty: 'foundation',
      question: 'Why is Operating Cash Flow considered the most vital indicator in financial analysis?',
      options: [
        'Because it shows how much tax the company can avoid',
        'Because it demonstrates the company’s ability to generate cash internally through its core operations without relying on external debt or equity injections',
        'Because it determines the market price of the company’s shares',
        'Because it replaces the need to prepare a Balance Sheet'
      ],
      correctAnswer: '1',
      rationale: 'Slide 8 highlights: Operating cash flow reveals whether the core business model can self-generate cash. If operating cash flow is negative, the company is completely dependent on external debt or shareholder subsidies to survive.',
      misconceptionTargeted: 'Viewing operating cash flow as merely an accounting formality.',
      revisitSection: '3.2 The 3 Cash Streams'
    },
    {
      id: 'm8-q6',
      moduleId: 'module-8',
      sourceTopic: 'Cash and Cash Equivalents Definition',
      type: 'mcq',
      difficulty: 'application',
      question: 'Which of the following items qualifies as "Cash and Cash Equivalents" according to Session 7 slides?',
      options: [
        'Trade receivables due in 60 days',
        'Short-term, highly liquid investments with an original maturity of ≤ 3 months and insignificant risk of value changes',
        'Listed shares acquired for long-term strategic control',
        'Unsold finished goods inventory stored in the warehouse'
      ],
      correctAnswer: '1',
      rationale: 'Cash equivalents are short-term, highly liquid investments readily convertible to known amounts of cash with insignificant risk of changes in value and original maturity ≤ 3 months.',
      misconceptionTargeted: 'Including trade receivables or inventories in cash equivalents.',
      revisitSection: '3.1 Profit vs Cash'
    },
    {
      id: 'm8-q7',
      moduleId: 'module-8',
      sourceTopic: 'Net Change in Cash Calculation',
      type: 'calculation',
      difficulty: 'exam-style',
      question: 'During 2026, a company reports:\n• Operating Cash Flow = +€42,000\n• Investing Cash Flow = -€5,000\n• Financing Cash Flow = -€10,000\n• Beginning Cash on 01/01/2026 = €63,000\nCalculate: (1) Net Change in Cash, and (2) Ending Cash balance on 31/12/2026.',
      correctAnswer: 'Net Change = +€27,000; Ending Cash = €90,000.',
      markingGuide: 'Net Change = 42,000 – 5,000 – 10,000 = 27,000. Ending Cash = 63,000 + 27,000 = 90,000.',
      rationale: 'Net Change in Cash [D] = A (+42,000) + B (-5,000) + C (-10,000) = +€27,000. Ending Cash [F] = Opening Cash [E] (€63,000) + Net Change [D] (€27,000) = €90,000.',
      misconceptionTargeted: 'Miscalculating signs or subtracting beginning cash.',
      revisitSection: '3.3 Reconciliation & Master Consistency Check'
    },
    {
      id: 'm8-q8',
      moduleId: 'module-8',
      sourceTopic: 'Disposal Proceeds in CFS',
      type: 'mcq',
      difficulty: 'application',
      question: 'When an old company vehicle is sold for €3,000 cash, where does the €3,000 appear in the Cash Flow Statement?',
      options: [
        'In Operating Cash Flow as sales revenue',
        'In Investing Cash Flow as proceeds from disposal of non-current assets (positive cash flow)',
        'In Financing Cash Flow as a disinvestment',
        'It is excluded from CFS because vehicles are fixed assets'
      ],
      correctAnswer: '1',
      rationale: 'Proceeds from the disposal of property, plant, and equipment represent cash recovered from capital investments, classified under Investing Cash Flow as a positive cash inflow.',
      misconceptionTargeted: 'Confusing asset disposal proceeds with commercial operating revenues.',
      revisitSection: '3.2 The 3 Cash Streams'
    },
    {
      id: 'm8-q9',
      moduleId: 'module-8',
      sourceTopic: 'Spot the Error',
      type: 'spot-the-error',
      difficulty: 'exam-style',
      question: 'A student prepared a forecast Cash Flow Statement and included:\n"Depreciation expense of equipment: -€15,000" inside Operating Activities.\nWhat is the fundamental error and how does it distort the statement?',
      correctAnswer: 'Depreciation is a NON-CASH expense! No cash was disbursed to anyone. Under the Direct Method, only actual physical collections and disbursements are recorded. Inserting -€15,000 wrongly understates operating cash flow and causes CFS closing cash to disagree with the Balance Sheet bank account by €15,000.',
      markingGuide: 'Must emphasize that depreciation is non-cash and that direct method CFS excludes non-cash accounting allocations.',
      rationale: 'Under the Direct Method CFS, cash flows are actual bank movements. Depreciation is purely an internal book entry (Debit 681 / Credit 281). Including it as a cash outflow creates a phantom cash reduction.',
      misconceptionTargeted: 'Treating depreciation as a cash outflow in the direct CFS.',
      revisitSection: '3.1 Profit vs Cash'
    },
    {
      id: 'm8-q10',
      moduleId: 'module-8',
      sourceTopic: 'Capital Increase in CFS',
      type: 'mcq',
      difficulty: 'foundation',
      question: 'A cash capital increase of €50,000 subscribed by shareholders is classified under which CFS stream?',
      options: [
        'Operating Cash Flow',
        'Investing Cash Flow',
        'Financing Cash Flow (Proceeds from issue of share capital)',
        'It is an exceptional item'
      ],
      correctAnswer: '2',
      rationale: 'Cash contributions from equity shareholders represent equity financing, classified under Financing Activities as a positive cash inflow.',
      misconceptionTargeted: 'Confusing equity financing with operating revenues.',
      revisitSection: '3.2 The 3 Cash Streams'
    },
    {
      id: 'm8-q11',
      moduleId: 'module-8',
      sourceTopic: 'Beethoven Case Cash Consistency Check',
      type: 'short-answer',
      difficulty: 'exam-style',
      question: 'In the Beethoven exam case answer key, what were the exact verified checks for: (1) Cash consistency, and (2) Accounting equation balance?',
      correctAnswer: 'Cash consistency: Cash from CFS (€14) = Cash from Balance Sheet (€14). Accounting equation: Assets (€410) = Equity (€238) + Liabilities (€172) = €410.',
      markingGuide: 'Award full marks for stating Cash = 14 on both CFS and BS, and Assets = 410 = Equity (238) + Liabilities (172).',
      rationale: 'In the official solution to the Beethoven final quiz: Cash from CFS (14) equals Cash from Balance Sheet (14). Total Assets (410) equals Equity (238) + Liabilities (172) = 410. Net Income from I/S (48) equals Net Income from B/S (48).',
      misconceptionTargeted: 'Failing to tie out the 3 checks on the final exam.',
      revisitSection: '3.3 Reconciliation & Master Consistency Check'
    },
    {
      id: 'm8-q12',
      moduleId: 'module-8',
      sourceTopic: 'Profitable Company Insolvent',
      type: 'true-false',
      difficulty: 'foundation',
      question: 'A company with substantial positive Net Income in its Income Statement can never face bankruptcy or insolvency during that fiscal year.',
      options: ['True', 'False', 'Don’t know'],
      correctAnswer: '1',
      rationale: 'False. A company can be highly profitable on paper (sales made on long credit terms), but suffer insolvency and bankruptcy if customer receivables are not collected in time to pay urgent supplier debts, salaries, and bank loans.',
      misconceptionTargeted: 'Believing accounting profit guarantees immediate cash solvency.',
      revisitSection: '3.1 Profit vs Cash'
    }
  ],
  worksheetBridge: {
    exerciseTitle: 'Windsurf Case (Part 5 / Session 7) — Forecast Financial Statements',
    exerciseFiles: [
      'Exercises/S7 - Windsurf (Part 5) - Case handout.pdf'
    ],
    context: 'Windsurf S7 is the ultimate rehearsal for the Beethoven final quiz. Starting with opening carrying values, you process 15 transactions (dividend payout, receivable collection, payable payment, revenue, opex, fixed asset purchase, depreciation, loan repayment, interest, and 25% CIT) and build the complete forecast Balance Sheet, P&L, and Cash Flow Statement.',
    finderGuidance: 'Open Exercises/S7 - Windsurf (Part 5) - Case handout.pdf in Finder. Complete the 3 statement templates.',
    stepChecklist: [
      'Carry forward opening balances from the prior year balance sheet.',
      'Record transactions 1 to 4 (prior year settlements & dividend appropriation).',
      'Compute provisional net change in cash.',
      'Record current operating transactions 5 to 10 (sales, purchases, opex, payroll).',
      'Record asset, borrowing, and interest transactions 11 to 14.',
      'Calculate pre-tax profit, determine CIT at 25%, and calculate net income.',
      'Compile the Direct Method Cash Flow Statement: Operating (A) + Investing (B) + Financing (C).',
      'PERFORM THE 3 CHECKS: (1) Assets = Equity + Liabilities; (2) Net Income I/S = Net Income B/S; (3) CFS Closing Cash = B/S Closing Cash!'
    ],
    templateHeaders: {
      given: 'Opening balance sheet and 15 business forecasts.',
      issue: 'Full cycle double-entry and forecast statement synthesis.',
      rule: 'Direct CFS: Operating + Investing + Financing = Net change; Ending Cash = Opening + Net change.',
      calculation: 'Cash collection and disbursement tables.',
      journalEntry: 'Forecast double-entry ledger.',
      profitEffect: 'Detailed multi-tier income statement.',
      positionEffect: 'Forecast balance sheet with verified equity and liabilities.',
      conclusion: 'Triple consistency confirmation (BS, IS, CFS).'
    }
  },
  recap: {
    takeaways: [
      'Profit is economic performance on paper; Cash is physical money in the bank.',
      'Non-cash items (depreciation, provisions, inventory variations) have ZERO impact on cash.',
      'The Cash Flow Statement separates cash into Operating (A), Investing (B), and Financing (C).',
      'Operating cash flow proves whether the core commercial model generates cash or consumes it.',
      'Closing CFS cash MUST strictly equal closing Balance Sheet cash (Line 512 + 53)!'
    ],
    recallPrompts: [
      '“Operating cash flow measures internal self-funding ability.”',
      '“Depreciation expense is non-cash and never appears in the direct CFS.”',
      '“CFS closing cash must match Balance Sheet closing cash to the penny.”'
    ],
    coreRule: 'Operating (A) + Investing (B) + Financing (C) = Net Change in Cash. Net Change + Opening Cash = Closing Cash on the Balance Sheet!'
  }
};
